name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Ajuste para a versão do seu projeto

      # Instalação do ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Adiciona ferramentas globais ao PATH
      - name: Add .NET tools to PATH
        run: |
          $env:Path += ";$([System.Environment]::GetFolderPath('UserProfile'))\.dotnet\tools"
          echo "Updated PATH: $env:Path"
        shell: pwsh

      # Restauração das dependências
      - name: Install dependencies
        run: dotnet restore

      # Build do projeto
      - name: Build
        run: dotnet build --no-restore

      # Execução dos testes
      - name: Run tests
        run: |
          dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./test-results
        shell: pwsh

      # Gerar o relatório de cobertura
      - name: Prepare code coverage report
        run: |
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:SonarQube
        shell: pwsh

      # Análise do SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      # Publish the test results
      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
